/**
 * Enterprise workspace mock data — 12 interactions across all 9 channel types.
 * Used as fallback when real backend data is unavailable or incomplete.
 */
import type { WorkspaceInteraction } from "./types";

const mkAI = (
  detected: boolean,
  confidence: number,
  sentiment: WorkspaceInteraction["ai"]["sentiment"],
  emotion: string,
  theme: string,
  severity: WorkspaceInteraction["ai"]["severity"],
  escRisk: number,
  slaRisk: WorkspaceInteraction["ai"]["slaRisk"],
  repeat: boolean,
  priorCount: number,
  summary: string,
  root: string,
  resolution: string,
  dept: string,
  response: string,
): WorkspaceInteraction["ai"] => ({
  complaintDetected: detected,
  detectionConfidence: confidence,
  sentiment,
  emotion,
  theme,
  severity,
  escalationRisk: escRisk,
  escalationRiskLevel:
    escRisk >= 75 ? "critical" : escRisk >= 50 ? "high" : escRisk >= 25 ? "medium" : "low",
  regulatoryRisk: escRisk >= 80,
  slaRisk,
  repeatComplaint: repeat,
  priorComplaintCount: priorCount,
  aiSummary: summary,
  rootCause: root,
  suggestedResolution: resolution,
  recommendedDepartment: dept,
  suggestedResponse: response,
  knowledgeArticles: [
    { title: "Claims Escalation Policy – Section 4.2", relevance: 94 },
    { title: "SLA Breach Compensation Guidelines", relevance: 87 },
    { title: "Customer Retention Protocol", relevance: 79 },
  ],
});

const mkCustomer = (
  id: string,
  name: string,
  phone: string,
  email: string,
  city: string,
  segment: string,
  since: string,
  policy: string,
  product: string,
  claim: string | null,
  risk: WorkspaceInteraction["customer"]["riskLevel"],
  totalC: number,
  openC: number,
  isRepeat: boolean,
  lastC: string | null,
  ltv: number,
): WorkspaceInteraction["customer"] => ({
  id,
  name,
  phone,
  email,
  city,
  segment,
  customerSince: since,
  policyNumber: policy,
  product,
  claimStatus: claim,
  riskLevel: risk,
  totalComplaints: totalC,
  openComplaints: openC,
  isRepeatCustomer: isRepeat,
  lastComplaint: lastC,
  lifetimeValue: ltv,
});

export const WORKSPACE_INTERACTIONS: WorkspaceInteraction[] = [
  // 1. WhatsApp — High Risk — Claim delay
  {
    id: "int-101",
    channel: "whatsapp",
    status: "high_risk",
    priority: "critical",
    time: "10:24 AM",
    timestamp: Date.now() - 5 * 60 * 1000,
    unreadCount: 3,
    subject: "Claim delayed for more than 2 weeks",
    lastMessage: "I have already called multiple times. Still no update!",
    customer: mkCustomer(
      "cust-001",
      "Fatima Al Lawati",
      "+968 9123 4567",
      "fatima.lawati@email.com",
      "Muscat, Oman",
      "Premium",
      "March 2021",
      "P-123456",
      "Motor Insurance",
      "CLM-2024-7812 – Pending",
      "high",
      4,
      2,
      true,
      "2 weeks ago",
      4800,
    ),
    messages: [
      { id: "m1", sender: "customer", type: "text", text: "My claim has been delayed for more than 2 weeks. No one is responding properly.", time: "10:21 AM", timestamp: Date.now() - 8 * 60 * 1000 },
      { id: "m2", sender: "agent", type: "text", text: "I understand your concern. Let me check the status of your claim and update you.", time: "10:22 AM", timestamp: Date.now() - 7 * 60 * 1000, agentName: "Ahmed Al Badi" },
      { id: "m3", sender: "customer", type: "text", text: "I have already called multiple times. Still no update. This is very frustrating!", time: "10:23 AM", timestamp: Date.now() - 6 * 60 * 1000 },
      { id: "m4", sender: "ai", type: "ai_note", text: "🤖 AI Alert: High complaint probability (94%). Claim delay detected. Escalation risk: Critical (92%). Recommend immediate escalation to Claims Manager.", time: "10:23 AM", timestamp: Date.now() - 6 * 60 * 1000 },
    ],
    ai: mkAI(true, 94, "very_negative", "Frustration / Anger", "Claim Delays", "high", 92, "at_risk", true, 4, "Customer is experiencing a 2-week claim delay with no updates. She has contacted us multiple times with no resolution. This is a repeat complaint pattern for this customer.", "Internal SLA breach — claim reassignment gap following adjuster vacation. No automated handover triggered.", "Immediately reassign claim to senior adjuster. Provide written update within 2 hours. Offer compensation consideration per SLA breach policy.", "Claims Resolution Team", "Dear Fatima, we sincerely apologize for the delay in processing your claim CLM-2024-7812. We have escalated this to our senior claims team and a dedicated officer will contact you within 2 hours with a full update."),
    assignedAgent: "Ahmed Al Badi",
  },
  // 2. Email — Refund not received
  {
    id: "int-102",
    channel: "email",
    status: "new",
    priority: "high",
    time: "10:15 AM",
    timestamp: Date.now() - 15 * 60 * 1000,
    unreadCount: 1,
    subject: "Policy P-987654 – Refund Not Received",
    lastMessage: "I cancelled my policy 3 weeks ago but haven't received my refund yet.",
    emailSubject: "Re: Policy P-987654 - Refund not received",
    emailFrom: "sultan.khalidi@email.com",
    emailRecipients: ["complaints@lumay.om"],
    emailAttachments: [
      { name: "cancellation_receipt.pdf", size: "142 KB" },
      { name: "bank_statement_june.pdf", size: "380 KB" },
    ],
    customer: mkCustomer("cust-002", "Sultan Al Khalidi", "+968 9332 5541", "sultan.khalidi@email.com", "Salalah, Oman", "Standard", "January 2022", "P-987654", "Home Insurance", null, "medium", 1, 1, false, null, 2100),
    messages: [
      { id: "m1", sender: "customer", type: "email", text: "Dear LuMay Team,\n\nI cancelled my home insurance policy (P-987654) on June 24th and was told I would receive a refund of OMR 45.000 within 5-7 business days. It has now been 3 weeks with no refund received.\n\nI have attached my cancellation receipt and bank statement as proof.\n\nPlease resolve this urgently.\n\nBest regards,\nSultan Al Khalidi", time: "10:15 AM", timestamp: Date.now() - 15 * 60 * 1000 },
      { id: "m2", sender: "ai", type: "ai_note", text: "🤖 AI: Financial complaint detected. Refund SLA likely breached (>15 days). Regulatory risk: Medium. Recommend Finance team escalation.", time: "10:15 AM", timestamp: Date.now() - 15 * 60 * 1000 },
    ],
    ai: mkAI(true, 88, "negative", "Frustration / Disappointment", "Payments & Refunds", "medium", 45, "at_risk", false, 1, "Customer cancelled policy 3 weeks ago and has not received the OMR 45 refund. SLA breach on refund processing. Financial complaint.", "Finance processing delay — refund batch not triggered due to system configuration issue on cancellation.", "Manually trigger refund processing. Confirm receipt within 24 hours. Send formal apology email.", "Finance & Billing Team", "Dear Sultan, we apologize for the delay in processing your refund. We have escalated your case to our Finance team as a priority. Your refund of OMR 45.000 will be processed within 2 business days and you will receive a confirmation email."),
    assignedAgent: null,
  },
  // 3. Web Chat — Renewal issue
  {
    id: "int-103",
    channel: "web_chat",
    status: "in_progress",
    priority: "medium",
    time: "10:10 AM",
    timestamp: Date.now() - 20 * 60 * 1000,
    unreadCount: 0,
    subject: "Unable to renew motor insurance online",
    lastMessage: "The system says my plate number is invalid.",
    customer: mkCustomer("cust-003", "Aisha Al Raisi", "+968 9221 4452", "aisha.raisi@email.com", "Sohar, Oman", "Standard", "July 2023", "P-654321", "Motor Insurance", null, "low", 0, 0, false, null, 1200),
    messages: [
      { id: "m1", sender: "system", type: "system_event", text: "Chat started — Aisha Al Raisi connected from lumay.om/my-policy", time: "10:08 AM", timestamp: Date.now() - 22 * 60 * 1000 },
      { id: "m2", sender: "customer", type: "text", text: "Hi, I am trying to renew my motor insurance online but the system says my plate number is invalid.", time: "10:10 AM", timestamp: Date.now() - 20 * 60 * 1000 },
      { id: "m3", sender: "agent", type: "text", text: "Hello Aisha! I can help with that. Please share your vehicle plate number and I'll check it on our end.", time: "10:11 AM", timestamp: Date.now() - 19 * 60 * 1000, agentName: "Sara Al Rashdi" },
      { id: "m4", sender: "customer", type: "text", text: "My plate is 12345 A Muscat. I updated the plate last month but the app still shows the old number.", time: "10:12 AM", timestamp: Date.now() - 18 * 60 * 1000 },
    ],
    ai: mkAI(false, 12, "neutral", "Confusion / Inquiry", "Digital Experience", "low", 12, "on_track", false, 0, "Customer is unable to renew motor insurance online due to plate number validation error. Likely a system sync issue after plate update.", "Vehicle plate number update was not synced to the policy management system after DMT notification.", "Update plate number in policy system. Enable online renewal. Offer 5% renewal discount as goodwill gesture.", "Digital Support Team", "Hi Aisha! I can see the issue — your plate number update hasn't synced to our renewal system yet. I'm updating it now. You should be able to renew online within 30 minutes. I'll also send you a direct renewal link."),
    assignedAgent: "Sara Al Rashdi",
  },
  // 4. Voice — Garage approval
  {
    id: "int-104",
    channel: "voice",
    status: "processed",
    priority: "low",
    time: "09:58 AM",
    timestamp: Date.now() - 32 * 60 * 1000,
    unreadCount: 0,
    subject: "(Call) Garage repair approval verification",
    lastMessage: "Calling to verify if my motor repair approval has been sent to the garage.",
    isLiveCall: false,
    callDuration: "4m 32s",
    customer: mkCustomer("cust-004", "Mohammed Al Hinai", "+968 9345 6789", "mohammed.hinai@email.com", "Nizwa, Oman", "Standard", "June 2020", "P-887766", "Motor Insurance", "CLM-2024-5521 – Active", "low", 1, 0, false, "3 months ago", 3200),
    messages: [
      { id: "m1", sender: "system", type: "system_event", text: "Inbound call connected — +968 9345 6789 — Queue: Claims Support", time: "09:55 AM", timestamp: Date.now() - 35 * 60 * 1000 },
      { id: "m2", sender: "customer", type: "voice_transcript", text: "[Customer] Calling to verify if my motor repair approval has been sent to the garage in Ghala. They said they didn't receive it.", time: "09:56 AM", timestamp: Date.now() - 34 * 60 * 1000 },
      { id: "m3", sender: "agent", type: "voice_transcript", text: "[Agent – Khalid] Yes Mr. Mohammed, I can see the approval was sent to Al Ghala Garage (GAR-1124) on the 14th. Let me resend it now to confirm receipt.", time: "09:57 AM", timestamp: Date.now() - 33 * 60 * 1000 },
      { id: "m4", sender: "customer", type: "voice_transcript", text: "[Customer] Thank you. How long will the repair take?", time: "09:58 AM", timestamp: Date.now() - 32 * 60 * 1000 },
      { id: "m5", sender: "system", type: "system_event", text: "Call ended — Duration: 4m 32s — Resolution: Resolved — Approval resent to garage", time: "09:59 AM", timestamp: Date.now() - 31 * 60 * 1000 },
    ],
    ai: mkAI(false, 8, "neutral", "Inquiry / Calm", "Provider & Garage", "low", 8, "resolved", false, 1, "Customer called to verify claim approval delivery to garage. Agent confirmed approval resent. Issue resolved in single call.", "Approval email delivery failure — garage email address bounced. Agent manually re-sent via portal.", "Resolved. Consider SMS backup notification to garages.", "Claims Support", ""),
    assignedAgent: "Khalid Al Farsi",
  },
  // 5. SMART CALL — AI Voice Agent
  {
    id: "int-105",
    channel: "smart_call",
    status: "processed",
    priority: "low",
    time: "09:45 AM",
    timestamp: Date.now() - 45 * 60 * 1000,
    unreadCount: 0,
    subject: "SMART CALL: Customer requested claim status update",
    lastMessage: "Is there any update on my medical claim from last Tuesday?",
    isLiveCall: false,
    callDuration: "2m 15s",
    customer: mkCustomer("cust-005", "Hamad Al Siyabi", "+968 9110 2233", "hamad.siyabi@email.com", "Muscat, Oman", "Standard", "November 2022", "P-109283", "Medical Insurance", "CLM-2024-8841 – Processing", "low", 0, 0, false, null, 1800),
    messages: [
      { id: "m1", sender: "system", type: "system_event", text: "SMART CALL initiated — AI Voice Agent handling — IVR Route: Claims Status", time: "09:43 AM", timestamp: Date.now() - 47 * 60 * 1000 },
      { id: "m2", sender: "customer", type: "voice_transcript", text: "[Customer] Is there any update on my medical claim from last Tuesday?", time: "09:44 AM", timestamp: Date.now() - 46 * 60 * 1000 },
      { id: "m3", sender: "agent", type: "voice_transcript", text: "[SMART AI Agent] I can see your medical claim CLM-2024-8841 is currently under review by our medical team. The expected decision date is July 17th. Would you like me to send you a WhatsApp update when the status changes?", time: "09:44 AM", timestamp: Date.now() - 46 * 60 * 1000 },
      { id: "m4", sender: "customer", type: "voice_transcript", text: "[Customer] Yes please. Thank you.", time: "09:45 AM", timestamp: Date.now() - 45 * 60 * 1000 },
      { id: "m5", sender: "system", type: "system_event", text: "SMART CALL resolved — WhatsApp notification subscription created — No human escalation required", time: "09:45 AM", timestamp: Date.now() - 45 * 60 * 1000 },
    ],
    ai: mkAI(false, 5, "neutral", "Calm / Satisfied", "Claim Status", "low", 5, "resolved", false, 0, "SMART CALL AI handled claim status inquiry end-to-end. Customer satisfied with response. Signed up for WhatsApp notifications.", "Routine inquiry handled by AI agent. No complaint detected.", "Continue SMART CALL handling. No human intervention needed.", "SMART CALL AI", ""),
    assignedAgent: "SMART AI Agent",
  },
  // 6. WhatsApp — High Risk — Road assistance
  {
    id: "int-106",
    channel: "whatsapp",
    status: "high_risk",
    priority: "critical",
    time: "09:30 AM",
    timestamp: Date.now() - 60 * 60 * 1000,
    unreadCount: 5,
    subject: "3-hour wait for road assistance — very bad experience",
    lastMessage: "I've been waiting 3 hours on the highway. This is terrible!",
    customer: mkCustomer("cust-006", "Khalid Al Maamari", "+968 9456 7890", "khalid.maamari@email.com", "Ibri, Oman", "Standard", "August 2021", "P-776655", "Motor Insurance", null, "high", 3, 1, true, "1 month ago", 2900),
    messages: [
      { id: "m1", sender: "customer", type: "text", text: "I've been waiting for road assistance for 3 hours on the highway. This service is terrible!", time: "09:30 AM", timestamp: Date.now() - 60 * 60 * 1000 },
      { id: "m2", sender: "ai", type: "ai_note", text: "🤖 AI Alert: Urgent situation — customer stranded on highway. Complaint detected (88% confidence). Escalation risk: Critical. Immediate human response required.", time: "09:30 AM", timestamp: Date.now() - 60 * 60 * 1000 },
    ],
    ai: mkAI(true, 88, "extremely_negative", "Anger / Distress", "Service Quality", "high", 88, "at_risk", true, 3, "Customer stranded on highway for 3+ hours with no road assistance. Critical service failure. High regulatory exposure.", "Third-party tow truck dispatch failure. Contractor GPS offline. No backup provider triggered.", "Immediately dispatch emergency response. Call customer now. Escalate to Service Manager. Log regulatory incident.", "Emergency Response Team", "Mr. Khalid, we sincerely apologize. We have immediately dispatched an emergency road assistance team to your location. Our service manager is calling you now. We will ensure you are safe and assisted within 20 minutes."),
    assignedAgent: null,
  },
  // 7. Email — Medical approval delay
  {
    id: "int-107",
    channel: "email",
    status: "in_progress",
    priority: "high",
    time: "09:18 AM",
    timestamp: Date.now() - 72 * 60 * 1000,
    unreadCount: 0,
    subject: "Complaint — Medical pre-authorization delay (4 hours)",
    lastMessage: "My dentist clinic is waiting 4 hours for treatment pre-authorization.",
    emailSubject: "Complaint: Medical pre-authorization delay",
    emailFrom: "maryam.farsi@email.com",
    emailRecipients: ["medical@lumay.om", "complaints@lumay.om"],
    emailAttachments: [{ name: "dentist_referral.pdf", size: "210 KB" }],
    customer: mkCustomer("cust-007", "Maryam Al Farsi", "+968 9877 6655", "maryam.farsi@email.com", "Sur, Oman", "Premium", "March 2020", "P-443322", "Medical Insurance", null, "medium", 2, 1, false, "3 months ago", 5100),
    messages: [
      { id: "m1", sender: "customer", type: "email", text: "Dear LuMay Medical Team,\n\nMy dentist clinic (Bright Smile, Muscat) has been waiting 4 hours for treatment pre-authorization for a root canal procedure. This delay is completely unacceptable and is causing my dentist to cancel my appointment.\n\nPlease escalate this immediately.\n\nMaryam Al Farsi\nPolicy: P-443322", time: "09:18 AM", timestamp: Date.now() - 72 * 60 * 1000 },
      { id: "m2", sender: "agent", type: "text", text: "Dear Maryam, we have received your complaint and are contacting the Medical Authorization team right now. We will have an update within 30 minutes.", time: "09:45 AM", timestamp: Date.now() - 55 * 60 * 1000, agentName: "Fatma Al Balushi" },
    ],
    ai: mkAI(true, 82, "negative", "Frustration", "Medical Approvals", "medium", 58, "at_risk", false, 2, "Medical pre-authorization delay of 4+ hours causing patient treatment disruption. Dental procedure at risk.", "Medical authorization queue backed up — understaffed Friday shift. No auto-escalation triggered after 2 hours.", "Immediately approve dental procedure. Apologize to patient and clinic. Review authorization SLA policy.", "Medical Authorization Team", "Dear Maryam, your dental pre-authorization for Bright Smile clinic has been approved (Auth: MED-2024-9921). We sincerely apologize for the 4-hour delay. Your dentist can proceed with the treatment immediately."),
    assignedAgent: "Fatma Al Balushi",
  },
  // 8. Web Chat — Billing query (closed)
  {
    id: "int-108",
    channel: "web_chat",
    status: "closed",
    priority: "low",
    time: "09:05 AM",
    timestamp: Date.now() - 85 * 60 * 1000,
    unreadCount: 0,
    subject: "Premium increased by 15 OMR — need clarification",
    lastMessage: "Can you clarify why my premium charge went up by 15 OMR this month?",
    customer: mkCustomer("cust-008", "Yousef Al Harthy", "+968 9555 4422", "yousef.harthy@email.com", "Muscat, Oman", "Standard", "October 2023", "P-221133", "Motor Insurance", null, "low", 0, 0, false, null, 900),
    messages: [
      { id: "m1", sender: "customer", type: "text", text: "Can you clarify why my premium charge went up by 15 OMR this month?", time: "09:05 AM", timestamp: Date.now() - 85 * 60 * 1000 },
      { id: "m2", sender: "agent", type: "text", text: "Hi Yousef! The increase is due to the annual motor insurance rate adjustment effective July 1st, which applies to all policies. The increase of OMR 15 reflects the new industry-mandated rates.", time: "09:08 AM", timestamp: Date.now() - 82 * 60 * 1000, agentName: "Noor Al Amri" },
      { id: "m3", sender: "customer", type: "text", text: "Oh I see. Thank you for the explanation.", time: "09:10 AM", timestamp: Date.now() - 80 * 60 * 1000 },
      { id: "m4", sender: "system", type: "system_event", text: "Chat closed — Customer satisfied — CSAT: ⭐⭐⭐⭐⭐", time: "09:11 AM", timestamp: Date.now() - 79 * 60 * 1000 },
    ],
    ai: mkAI(false, 10, "neutral", "Curious / Neutral", "Billing", "low", 10, "resolved", false, 0, "Customer queried premium increase. Agent explained rate adjustment. Resolved in single interaction with positive CSAT.", "Annual rate adjustment — no system issue.", "Resolved. No action needed.", "Billing Support", ""),
    assignedAgent: "Noor Al Amri",
  },
  // 9. CRM — VIP customer history
  {
    id: "int-109",
    channel: "crm",
    status: "in_progress",
    priority: "high",
    time: "08:45 AM",
    timestamp: Date.now() - 105 * 60 * 1000,
    unreadCount: 2,
    subject: "VIP Customer — Multiple policy review requested",
    lastMessage: "3 interactions logged since last week",
    customer: mkCustomer("cust-009", "Saif Al Rawahi", "+968 9688 1122", "saif.rawahi@email.com", "Muscat, Oman", "VIP", "January 2015", "P-000001", "Business Fleet", "CLM-2024-1001 – Active", "medium", 7, 1, true, "1 week ago", 28000),
    messages: [
      { id: "m1", sender: "agent", type: "text", text: "CRM Note (July 8): Customer called to discuss renewal of fleet policy. Discussed premium adjustment. Assigned to relationship manager.", time: "08:00 AM Jul 8", timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000, agentName: "Mohammed Al Khanjari" },
      { id: "m2", sender: "agent", type: "text", text: "CRM Note (July 10): Follow-up call. Customer requested custom policy for 2 new vehicles added to fleet. Passed to underwriting.", time: "09:30 AM Jul 10", timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000, agentName: "Mohammed Al Khanjari" },
      { id: "m3", sender: "agent", type: "text", text: "CRM Note (July 14): Underwriting approved new vehicle additions. Customer satisfied. Sent revised policy document.", time: "02:15 PM Jul 14", timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000, agentName: "Ahmed Al Badi" },
      { id: "m4", sender: "system", type: "system_event", text: "Task assigned: Relationship Manager check-in scheduled for July 20th", time: "08:45 AM", timestamp: Date.now() - 105 * 60 * 1000 },
    ],
    ai: mkAI(false, 15, "positive", "Satisfied / Engaged", "Policy & Coverage", "low", 15, "on_track", true, 7, "VIP customer with 28,000 OMR lifetime value. Currently managing fleet policy expansion. Relationship in good standing.", "Routine relationship management interaction.", "Continue proactive check-ins. Offer loyalty renewal discount at next cycle.", "Relationship Management", ""),
    assignedAgent: "Mohammed Al Khanjari",
  },
  // 10. Manual — Walk-in complaint
  {
    id: "int-110",
    channel: "manual",
    status: "new",
    priority: "high",
    time: "08:30 AM",
    timestamp: Date.now() - 120 * 60 * 1000,
    unreadCount: 1,
    subject: "Branch walk-in — Claim rejection complaint",
    lastMessage: "Customer walked into Muscat HQ branch to dispute rejected claim",
    customer: mkCustomer("cust-010", "Ibrahim Al Tobi", "+968 9221 9090", "ibrahim.tobi@email.com", "Muscat, Oman", "Standard", "May 2019", "P-556677", "Home Insurance", "CLM-2024-3344 – Rejected", "high", 2, 1, false, "1 month ago", 3500),
    messages: [
      { id: "m1", sender: "agent", type: "text", text: "Manual Entry (Branch – Muscat HQ): Customer Ibrahim Al Tobi walked into the branch at 08:30 to dispute his rejected home insurance claim (CLM-2024-3344). He presented original receipts and photos of water damage. He is requesting a review of the rejection decision.", time: "08:30 AM", timestamp: Date.now() - 120 * 60 * 1000, agentName: "Branch Agent – Fatma" },
      { id: "m2", sender: "ai", type: "ai_note", text: "🤖 AI: Formal complaint. Walk-in claim dispute. Previous claim (CLM-2023-7700) also involved home damage — pattern detected. Recommend Senior Adjuster review.", time: "08:30 AM", timestamp: Date.now() - 120 * 60 * 1000 },
    ],
    ai: mkAI(true, 85, "negative", "Anger / Determination", "Claims", "high", 72, "at_risk", false, 2, "Customer walked in to dispute rejected home insurance claim for water damage. Presented physical evidence. Possible claims assessment error.", "Automated claim assessment may have misclassified water damage as excluded flood damage. No adjuster physical inspection.", "Re-open claim for senior adjuster review. Schedule property inspection. Issue formal acknowledgment letter.", "Claims Review Board", "Dear Mr. Ibrahim, we acknowledge your formal complaint regarding claim CLM-2024-3344. We are re-opening your claim for senior adjuster review and will schedule a property inspection within 48 hours. You will receive a formal written response within 5 business days."),
    assignedAgent: "Branch Agent – Fatma",
  },
  // 11. Survey — Post-claim satisfaction
  {
    id: "int-111",
    channel: "survey",
    status: "processed",
    priority: "medium",
    time: "08:15 AM",
    timestamp: Date.now() - 135 * 60 * 1000,
    unreadCount: 0,
    subject: "Post-claim CSAT Survey — Policy P-334455",
    lastMessage: "Survey completed — Score: 3/10",
    surveyScore: 3,
    surveyResponses: [
      { question: "How satisfied are you with the claims resolution speed?", answer: "Very unsatisfied — it took 6 weeks", rating: 1 },
      { question: "How professional was the claims adjuster?", answer: "Somewhat professional but lacked knowledge of my specific coverage", rating: 3 },
      { question: "How likely are you to renew with LuMay?", answer: "Unlikely", rating: 2 },
      { question: "What would improve your experience?", answer: "Faster processing and better communication about claim status" },
      { question: "Overall satisfaction rating", answer: "3 out of 10", rating: 3 },
    ],
    customer: mkCustomer("cust-011", "Nadia Al Balushi", "+968 9334 5566", "nadia.balushi@email.com", "Muscat, Oman", "Standard", "February 2023", "P-334455", "Medical Insurance", "CLM-2024-6612 – Resolved", "medium", 1, 0, false, "6 weeks ago", 1400),
    messages: [
      { id: "m1", sender: "customer", type: "text", text: "Survey submitted via SMS link — Overall Score: 3/10", time: "08:15 AM", timestamp: Date.now() - 135 * 60 * 1000 },
      { id: "m2", sender: "ai", type: "ai_note", text: "🤖 AI: Low CSAT score (3/10). Churn risk: High. Recommend proactive retention call within 24 hours. Complaint probability: 78%.", time: "08:15 AM", timestamp: Date.now() - 135 * 60 * 1000 },
    ],
    ai: mkAI(false, 78, "negative", "Disappointment", "Customer Service", "medium", 40, "resolved", false, 1, "Customer submitted low satisfaction survey (3/10) following medical claim resolution. Dissatisfied with processing speed and communication. Churn risk is high.", "6-week claim processing time significantly exceeded customer expectations. Communication gaps throughout.", "Proactive retention call from senior agent. Offer loyalty incentive. Improve claim communication cadence.", "Customer Retention Team", "Dear Nadia, we noticed your recent survey response and want to personally reach out to address your concerns..."),
    assignedAgent: null,
  },
  // 12. Claims Notes — Internal adjuster notes
  {
    id: "int-112",
    channel: "claims",
    status: "in_progress",
    priority: "high",
    time: "07:50 AM",
    timestamp: Date.now() - 160 * 60 * 1000,
    unreadCount: 0,
    subject: "Claims Notes — Motor Accident CLM-2024-9955",
    lastMessage: "Adjuster: Vehicle total loss confirmed. Awaiting valuation.",
    claimNumber: "CLM-2024-9955",
    adjusterName: "Hassan Al Habsi",
    customer: mkCustomer("cust-012", "Omar Al Zadjali", "+968 9770 3344", "omar.zadjali@email.com", "Muscat, Oman", "Premium", "April 2018", "P-112233", "Motor Insurance", "CLM-2024-9955 – Active", "medium", 3, 1, false, "2 months ago", 7200),
    messages: [
      { id: "m1", sender: "agent", type: "text", text: "Adjuster Note (Hassan Al Habsi, July 13): Vehicle inspected at impound yard (Ghubra). Damage assessment: Total loss. Engine destroyed. Chassis bent. Market value estimate: OMR 8,200 based on 2021 Toyota Prado similar spec.", time: "10:30 AM Jul 13", timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000, agentName: "Hassan Al Habsi" },
      { id: "m2", sender: "agent", type: "text", text: "Surveyor Note (External – Al Mukhtar Survey): Independent assessment confirms total loss. Market valuation: OMR 8,000–8,400. Recommend settlement at OMR 8,200.", time: "02:00 PM Jul 13", timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000, agentName: "External Surveyor" },
      { id: "m3", sender: "agent", type: "text", text: "Adjuster Note (Hassan Al Habsi, July 15): Settlement offer letter sent to customer via email. Awaiting customer acceptance. Ownership transfer docs also sent.", time: "07:50 AM", timestamp: Date.now() - 160 * 60 * 1000, agentName: "Hassan Al Habsi" },
    ],
    ai: mkAI(false, 20, "neutral", "Cooperative", "Claims", "medium", 25, "on_track", false, 3, "Motor vehicle total loss claim. Dual assessment confirmed OMR 8,200 settlement. Awaiting customer acceptance. Process on track.", "Road accident — not a service failure. Claim being processed correctly.", "Continue claim processing. Ensure settlement is paid within 5 business days of acceptance.", "Claims Settlement Team", ""),
    assignedAgent: "Hassan Al Habsi",
  },
];
