"""Analytics domain Pydantic schemas."""
from domains.analytics.schemas.analytics_schemas import (
    AIAnalytics,
    AnalyticsReport,
    CategoryDistribution,
    ComplaintTrends,
    CustomerMetrics,
    DashboardKPIs,
    DepartmentWorkload,
    NotificationAnalytics,
    PriorityDistribution,
    ResolutionMetrics,
    SLACompliance,
    SentimentDistribution,
    SeverityDistribution,
    TrendPoint,
    WorkflowAnalytics,
)

__all__ = [
    "AIAnalytics",
    "AnalyticsReport",
    "CategoryDistribution",
    "ComplaintTrends",
    "CustomerMetrics",
    "DashboardKPIs",
    "DepartmentWorkload",
    "NotificationAnalytics",
    "PriorityDistribution",
    "ResolutionMetrics",
    "SLACompliance",
    "SentimentDistribution",
    "SeverityDistribution",
    "TrendPoint",
    "WorkflowAnalytics",
]