"""phase2_ai_fields

Revision ID: 9b1ab922e651
Revises: 20260714_0900
Create Date: 2026-07-14 22:16:48.076827
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '9b1ab922e651'
down_revision: Union[str, None] = '20260714_0900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('theme_secondary', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('theme_keywords', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('auto_escalation_triggers', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('complaint_detected', sa.Boolean(), nullable=True))
    op.add_column('complaints', sa.Column('detection_type', sa.String(length=20), nullable=True))
    op.add_column('complaints', sa.Column('detection_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('primary_complaint_statement', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_start', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_end', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_trend', sa.String(length=20), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_target', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_polarity', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_intensity', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('sentiment_emotions', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('escalation_risk_score', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('escalation_risk_level', sa.String(length=20), nullable=True))
    op.add_column('complaints', sa.Column('escalation_triggers', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('sla_risk', sa.String(length=20), nullable=True))
    op.add_column('complaints', sa.Column('sla_breach_probability', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('sla_hours_remaining', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('is_repeat', sa.Boolean(), nullable=True))
    op.add_column('complaints', sa.Column('repeat_window_days', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('prior_complaint_ids', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('prior_complaint_count', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('root_cause_category', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('contributing_factors', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('process_failure_point', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('detected_language', sa.String(length=10), nullable=True))
    op.add_column('complaints', sa.Column('arabic_percentage', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('ai_explanation', sa.JSON(), nullable=True))
    op.add_column('complaints', sa.Column('routing_rule', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('suggested_response_template', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('ai_override_log', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_complaints_theme'), 'complaints', ['theme'], unique=False)
    op.drop_column('complaints', 'risk_score')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### end Alembic commands ###

    op.drop_column('complaints', 'suggested_response_template')
    op.drop_column('complaints', 'routing_rule')
    op.drop_column('complaints', 'ai_explanation')
    op.drop_column('complaints', 'arabic_percentage')
    op.drop_column('complaints', 'detected_language')
    op.drop_column('complaints', 'process_failure_point')
    op.drop_column('complaints', 'contributing_factors')
    op.drop_column('complaints', 'root_cause_category')
    op.drop_column('complaints', 'root_cause')
    op.drop_column('complaints', 'prior_complaint_count')
    op.drop_column('complaints', 'prior_complaint_ids')
    op.drop_column('complaints', 'repeat_window_days')
    op.drop_column('complaints', 'is_repeat')
    op.drop_column('complaints', 'priority_score')
    op.drop_column('complaints', 'sla_hours_remaining')
    op.drop_column('complaints', 'sla_breach_probability')
    op.drop_column('complaints', 'sla_risk')
    op.drop_column('complaints', 'escalation_triggers')
    op.drop_column('complaints', 'escalation_risk_level')
    op.drop_column('complaints', 'escalation_risk_score')
    op.drop_column('complaints', 'sentiment_emotions')
    op.drop_column('complaints', 'sentiment_intensity')
    op.drop_column('complaints', 'sentiment_polarity')
    op.drop_column('complaints', 'sentiment_target')
    op.drop_column('complaints', 'sentiment_trend')
    op.drop_column('complaints', 'sentiment_end')
    op.drop_column('complaints', 'sentiment_start')
    op.drop_column('complaints', 'primary_complaint_statement')
    op.drop_column('complaints', 'detection_confidence')
    op.drop_column('complaints', 'detection_type')
    op.drop_column('complaints', 'complaint_detected')
    op.drop_column('complaints', 'auto_escalation_triggers')
    op.drop_column('complaints', 'theme_keywords')
    op.drop_column('complaints', 'theme_secondary')
    # ### end Alembic commands ###
