import { MoreHorizontal, Download, ChevronLeft, ChevronRight, FileText, FileSpreadsheet } from "lucide-react";

// TODO: Replace with API-driven type once the reports endpoint is available
type MockReport = {
  name: string;
  description: string;
  type: string;
  typeBg: string;
  typeColor: string;
  period: string;
  generatedOn: string;
  generatedBy: string;
  format: "PDF" | "XLSX";
};

// Will be populated from the API — kept as an empty placeholder until integration
const MOCK_REPORTS: MockReport[] = [];

type ReportsTableProps = {
  activeTab: string;
};

export function ReportsTable({ activeTab }: ReportsTableProps) {
  return (
    <div className="bg-white border border-[#E2E8F0] rounded-2xl shadow-sm overflow-hidden flex flex-col w-full text-left">
      {/* Table Content */}
      <div className="overflow-x-auto">
        <table className="w-full min-w-[900px] border-collapse">
          <thead>
            <tr className="border-b border-[#F1F5F9] bg-[#F8FAFC] text-[10px] font-extrabold uppercase tracking-wider text-slate-400">
              <th className="px-5 py-4">Report Name</th>
              <th className="px-5 py-4">Description</th>
              <th className="px-5 py-4">Type</th>
              <th className="px-5 py-4">Period</th>
              <th className="px-5 py-4">Generated On</th>
              <th className="px-5 py-4">Generated By</th>
              <th className="px-5 py-4">Format</th>
              <th className="px-5 py-4 w-24 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#F1F5F9] text-xs font-bold text-[#0F172A]">
            {MOCK_REPORTS.map((row) => (
              <tr key={row.name} className="hover:bg-[#F8FAFC] transition-colors">
                <td className="px-5 py-3.5 text-[#0052FF] hover:underline cursor-pointer">
                  {row.name}
                </td>
                <td className="px-5 py-3.5 text-slate-400 font-semibold max-w-[240px] truncate">
                  {row.description}
                </td>
                <td className="px-5 py-3.5">
                  <span className={`inline-block rounded-lg px-2.5 py-0.5 text-[10px] font-bold ${row.typeBg} ${row.typeColor}`}>
                    {row.type}
                  </span>
                </td>
                <td className="px-5 py-3.5 text-[#475569] font-semibold">
                  {row.period}
                </td>
                <td className="px-5 py-3.5 text-[#475569]">
                  {row.generatedOn}
                </td>
                <td className="px-5 py-3.5 text-[#475569]">
                  {row.generatedBy}
                </td>
                <td className="px-5 py-3.5">
                  {row.format === "PDF" ? (
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold text-red-600 bg-red-50 border border-red-100 rounded-lg px-2.5 py-0.5">
                      <FileText className="h-3 w-3 shrink-0" />
                      {row.format}
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold text-green-600 bg-green-50 border border-green-100 rounded-lg px-2.5 py-0.5">
                      <FileSpreadsheet className="h-3 w-3 shrink-0" />
                      {row.format}
                    </span>
                  )}
                </td>
                <td className="px-5 py-3.5 text-center">
                  <div className="flex items-center justify-center gap-2">
                    <button className="flex h-7 w-7 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-400 hover:text-slate-600 hover:bg-slate-50 transition-all shadow-sm">
                      <Download className="h-4 w-4" />
                    </button>
                    <button className="flex h-7 w-7 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-400 hover:text-slate-600 hover:bg-slate-50 transition-all shadow-sm">
                      <MoreHorizontal className="h-4 w-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Footer Info Pagination */}
      <div className="flex items-center justify-between border-t border-[#F1F5F9] px-5 py-4 bg-white text-xs font-bold text-[#64748B]">
        <div>Showing 1 to 6 of 24 reports</div>
        <div className="flex items-center gap-1.5">
          <button className="h-8 w-8 flex items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-400 hover:text-slate-600 transition-all shadow-sm">
            <ChevronLeft className="h-4 w-4" />
          </button>
          <button className="h-8 w-8 flex items-center justify-center rounded-xl border border-[#0052FF] bg-[#EFF6FF] text-[#0052FF] shadow-sm">
            1
          </button>
          <button className="h-8 w-8 flex items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 transition-all shadow-sm">
            2
          </button>
          <button className="h-8 w-8 flex items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 transition-all shadow-sm">
            3
          </button>
          <span className="px-1 text-slate-400">...</span>
          <button className="h-8 px-2.5 flex items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 transition-all shadow-sm">
            4
          </button>
          <button className="h-8 w-8 flex items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-400 hover:text-slate-600 transition-all shadow-sm">
            <ChevronRight className="h-4 w-4" />
          </button>

          {/* Selector */}
          <div className="relative ml-2">
            <select className="h-8 rounded-xl border border-slate-200 bg-white px-2.5 pr-7 text-xs font-bold text-slate-700 focus:outline-none shadow-sm cursor-pointer appearance-none">
              <option>10 / page</option>
              <option>20 / page</option>
              <option>50 / page</option>
            </select>
            <div className="absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-[#64748B]" />
          </div>
        </div>
      </div>
    </div>
  );
}